version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/gofiber/fiber/v2
    versions:
    - 2.4.0
    - 2.4.1
    - 2.5.0
    - 2.6.0
    - 2.7.1
  - dependency-name: github.com/huandu/go-sqlbuilder
    versions:
    - 1.11.0
    - 1.12.0
  - dependency-name: github.com/sirupsen/logrus
    versions:
    - 1.7.1
    - 1.8.0
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
